### ISSUE TITLE
Pristine Objects in the Depths

### ISSUE THREAD

**Issue by CeruleanSky** [vetyst/TotK-Object-Map#10]
Hello again, perhaps you haven't gotten to these objects yet or they are harder to locate, but I found a Pristine Royal Claymore ( Weapon_Lsword_024 ) held by a negative ghost stand, just a few minutes ago I tried looking for it on the object map and noticed there were none.
These are all the objects available when selecting show all, I removed them one by one to confirm that there was nothing left remaining:
<details>
<summary>All objects that are in the map</summary>

![all objects that are in the map](https://github.com/vetyst/TotK-Object-Map/assets/2829875/1303009b-7a68-4cb0-8cd7-1702566d4b6e)
</details>
<details>
<summary>In game maps and photos</summary>

![Photo of Sword](https://github.com/vetyst/TotK-Object-Map/assets/2829875/dc5fcfa9-4458-419f-82b5-cbbc17d54c58)
![zoomed in map](https://github.com/vetyst/TotK-Object-Map/assets/2829875/5e43dd26-0553-427b-a6bc-99b7a0cfd42b)
![Zoomed Out Map](https://github.com/vetyst/TotK-Object-Map/assets/2829875/be0f8fc4-cb2f-44cd-b96a-21fa64bb8ced)

</details>

Thanks again for creating this.

**Comment by danny-janse** [comment]
Thanks for letting me know! I've yet to figure out how the 'loot table' is accessed for the Ghost. They have no specific weapon assigned. atleast not that i can see in the files. yet.

i'll update you if i know more!

**Comment by armuell** [comment]
I believe the weapons held by ghosts are based on scaling. I don't have solid proof of this but based on my observations during my casual playthrough I noticed royal weapons a lot more after killing many field bosses and clearing a couple of dungeons. Also after checking the depths on a fresh file I noticed all gear was exclusively "Traveler's X" weapons held by ghost (I checked ~15 of them).

**Comment by frdulzuro** [comment]
If it helps any I'm pretty sure the ghosts are "Npc_MinusFieldGhost_000". The pristine weapons only spawn if you have destroyed a non pristine version of the weapon. Scaling doesn't seem to affect it as I have checked it on a fresh save. As for the 'loot table' the data seems to store only the type of weapon "HoldingWeaponType" 1,2,3 or undefined. I think the undefined might be a basic non scaling table but unsure. My guess would be that the table is based on where in the map it is (A-J, 1-8). So far my quick testing seems to confirm that any ghosts in the same area with the same HoldingWeaponType have the same loot table. For example A1 HoldingWeaponType=2 seem to have Soldiers Claymore, Knights Claymore, and Royal Claymore. I can't confirm this is true across the board as it takes some time to test each one but so far it has been consistent.

**Comment by CeruleanSky** [comment]
There has been some progress since this issue has been opened, Echocolat has released a script and maps of the pristine weapons 
https://github.com/Echocolat/totk-pristine_weapons

Description of the process at the bottom of their reddit post
https://www.reddit.com/r/tearsofthekingdom/comments/13uqo9h/everything_you_need_to_know_about_nondecayed/

Rules of what random weapons can spawn and their requirements are also included in the post.

**Comment by danny-janse** [comment]
@CeruleanSky thank you for delivering these resources. However, since this process is procedurally generated and heavily influenced by RNG it is not something that is and will be included for this project.
