### ISSUE TITLE
Npc_HiddenKorokFly are also Koroks

### ISSUE THREAD

**Issue by guspolly** [vetyst/TotK-Object-Map#11]
Currently only the Npc_HiddenKorokGround objects are labeled as Koroks. Those are the ones that are standing on the ground, the Npc_HiddenKorokFly are the ones that are flying. Counting them up, 425 flying and 318 standing on the surface, and 38 flying and 19 standing in the sky, equal exactly 800 Koroks.

**Comment by irritant4** [comment]
Here is how I count up to all 1000 Koroks

case "Npc_HiddenKorokGround":
case "Npc_HiddenKorokFly":

these are counted as (1) each

case "KorokCarry_Destination_Backpack"

are counted as (2) each

on the [Surface] that is 939 then there is an additional 61 in the [Sky] = 1000

Also, I draw a polyline from "KorokCarryPassenger_Pair" to "KorokCarry_Destination_Backpack"

**Comment by danny-janse** [comment]
Using @irritant4's information above i've made a preset for all of 900 krokok (1000 seed) locations.
