### ISSUE TITLE
Can't find silver lynels

### ISSUE THREAD

**Issue by flipperbw** [vetyst/TotK-Object-Map#12]
I see some markers for white, blue, etc. but nothing for silver.

**Comment by danny-janse** [comment]
Silver Lynels are generated over time. Lynels that are non-specific will scale as the world's difficulty ramps up. What specificly increases the difficulty in TotK is yet unknown. A detailed explanation for botw in this video. I would expect TotK to work similairly. https://www.youtube.com/watch?v=rWFy8v9snfs&pp=ygUSYm90dyB3b3JsZCBzY2FsaW5n
