### ISSUE TITLE
Cant find bomb flowers

### ISSUE THREAD

**Issue by navvv6** [vetyst/TotK-Object-Map#13]
There is only a few bomb flowers on the map, where are the rest of them?
As opposed to hyrule herb (700+ location) surely there is more than 15 bomb flowers on all of the map?
thanks for this amazing resource

**Comment by danny-janse** [comment]
You can change which which layer you're searching for using these 4 buttons. That should allow you to find the other locations of bomb flowers which are are over 6500 in total.

![image](https://github.com/vetyst/TotK-Object-Map/assets/3527340/2dd5f206-ef33-46d1-96be-9228a417b368)
