### ISSUE TITLE
Gerudo shield missing

### ISSUE THREAD

**Issue by navb104** [vetyst/TotK-Object-Map#14]
![image](https://github.com/vetyst/TotK-Object-Map/assets/108943285/3b1ed289-b638-4270-b93a-2eaddbdc1912)
![image](https://github.com/vetyst/TotK-Object-Map/assets/108943285/3cee213c-c431-4190-a8e7-c0b5694b583c)
Here are the coords of a shield in game along with my position. Does anyone know where the shield is?

**Comment by danny-getsturdy** [comment]
Could this be similair to the silent princesses in the vortex with the 13th dragon tear? They're locked behind quests?

**Comment by danny-janse** [comment]
This item is only available during a certain instance called  "Set_Defense_Courtyard_Goods_c7ea_2ace".  Given the name, probably only during the Tower Defense sequence.
