### ISSUE TITLE
Map Presets

### ISSUE THREAD

**Issue by irritant4** [vetyst/TotK-Object-Map#15]
I looked at MrCheese's original code for his presets:

$('input[name="' + presets[name][i] + '"]').prop('checked', true).trigger("change");

He is using this to check the boxes on his list therefore creating presets.

I see in your code:

jQuery('#item-filters .' + activeLayer + ' label[data-search-value="' + presets[name][i] + '"]').show();

But for the life of me cannot get it to do something similar. I want to do the exact same thing as MrCheese's presets but with your map.

**Comment by danny-janse** [comment]
This has become a feature now.
