### ISSUE TITLE
Possible Missing Items due to May 26th Changes

### ISSUE THREAD

**Issue by CeruleanSky** [vetyst/TotK-Object-Map#8]
I was searching for Steel Lizos Bows (weapon_bow_030) and I noticed they were returned on May 25th's version for the surface since I took a picture.  I haven't been able to reach the area shown yet to confirm if they were real or a bug, but just wanted to let you know in case this was unexpected behavior.

May 25
![image](https://github.com/vetyst/TotK-Object-Map/assets/2829875/fdfe426d-6fb6-4ad9-8afa-642584f4f074)

May 26
![image](https://github.com/vetyst/TotK-Object-Map/assets/2829875/1f749c00-692d-46bb-af5d-7b2feed84169)

**Comment by danny-janse** [comment]
I think i forgot to add back the castle data. Let me make sure the items from this file are actually there tho.

**Comment by danny-janse** [comment]
@CeruleanSky These objects have been restored.
